//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceMaintanance.Core.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceRequestStatu
    {
        public long Id { get; set; }
        public long ServiceRequestId { get; set; }
        public int Status { get; set; }
        public string Comment { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ServiceRequest ServiceRequest { get; set; }
    }
}
